version: '3.8'

services:
  backend-flask:
    build:
      context: .
      dockerfile: ./DockerfileGPT
    expose:
      - "5000"
    env_file:
      - ./flask-backend/gpt_library/.env
    volumes:
      - ./flask-backend:/app

  frontend-next:
    build:
      context: .
      dockerfile: ./DockerfileNext
    expose:
      - "3000"
    volumes:
      - ./next-frontend:/app
    environment:
      - NODE_ENV=development

  nginx-reverse-proxy:
      build:
        context: .
        dockerfile: ./Dockerfile-nginx-reverse-proxy
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - backend-flask
        - frontend-next
      restart: always
