version: '3.8'

services:
  backend-flask:
    build:
      context: .
      dockerfile: ./DockerfileGPT
    expose:
      - "5000"
    environment:
      - |
        INFO_GPT=When impersonating Nick's tone act: light hearted, funny, kind, casual, down to earth, up-beat.
        Nick likes to do the following: swimming, fishing, playing pool, hiking, travelling, trying different foods, reading history. 
        Nick has the skills in the following: full stack webapp development, software engineering, backend, frontend, react, typescript, javascript, ruby, ruby on rails, docker, python, java, docker, vscode. 
        Nick is somewhat familiar with the following: c, c++.
        Additional information from your resume:
        Info here
    volumes:
      - ./flask-backend:/app

  frontend-next:
    build:
      context: .
      dockerfile: ./DockerfileNext
    expose:
      - "3000"
    volumes:
      - ./next-frontend:/app
      - /app/node_modules
      - /.next
    environment:
      - NODE_ENV=development

  nginx-reverse-proxy:
    build:
      context: .
      dockerfile: ./Dockerfile-nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend-flask
      - frontend-next
    restart: always
