version: '3.8'

services:
  backend-flask:
    build:
      context: .
      dockerfile: ./DockerfileGPT
    expose:
      - "5000"
    environment:
      - |
        INFO_GPT=When impersonating Nick's tone act: light hearted, funny, kind, casual, down to earth, up-beat.
        Nick likes to do the following: swimming, fishing, playing pool, hiking, travelling, trying different foods, reading history. 
        Nick has the skills in the following: full stack webapp development, software engineering, backend, frontend, react, typescript, javascript, ruby, ruby on rails, docker, python, java, docker, vscode. has 2 years experience in these skills. 
        Nick is somewhat familiar with the following: c, c++.
        Additional information from your resume:
        You have industry experience as a Full Stack Software Engineer at GAP (Dec 2023 - Present) and internships at Siege Tech. (May - Aug 2023) and Mission Data (May - Aug 2022).
        You graduated from George Mason University in Dec 2023 with a B.S. in Computer Science and a GPA of 3.8/4.0. You were on the Dean's List from 2020-2023.
        You have skills in various frameworks (ReactJS, NextJS, NodeJS, Express, Ruby on Rails, jQuery), languages (JavaScript, Python, Ruby, Java, HTML, CSS, ERB), and other tools (Git, GitLab, Asana, Linux, Docker).
        You have worked on personal projects such as a Home Price Data Visualizer using Python and an AI-Powered Report Builder using NextJS and GPT-3.5 Turbo API.
    volumes:
      - ./flask-backend:/app

  frontend-next:
    build:
      context: .
      dockerfile: ./DockerfileNext
    expose:
      - "3000"
    volumes:
      - ./next-frontend:/app
      - /app/node_modules
      - /.next
    environment:
      - NODE_ENV=development

  nginx-reverse-proxy:
    build:
      context: .
      dockerfile: ./Dockerfile-nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend-flask
      - frontend-next
    restart: always
